version: '3.4'

# Specify feature configuration for all nodes at once
# See AntidoteDB documentation on how to configure these features
x-antidote-features:
  &default-features
  RING_SIZE: "12"
  ANTIDOTE_TXN_CERT: "true"
  ANTIDOTE_TXN_PROT: "clocksi"
  ANTIDOTE_RECOVER_FROM_LOG: "true"
  ANTIDOTE_META_DATA_ON_START: "true"
  ANTIDOTE_SYNC_LOG: "false"
  ANTIDOTE_ENABLE_LOGGING: "true"
  ANTIDOTE_AUTO_START_READ_SERVERS: "true"
  COOKIE: "secret"


services:
  dc1n1:
    container_name: dc1n1
    image: antidotedb/antidote:latest
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc1n1"
    ports:
      - "8101:8087"
      - "8102:3001"

  dc1n2:
    container_name: dc1n2
    image: antidotedb/antidote:latest
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc1n2"
    ports:
      - "8201:8087"
      - "8202:3001"

  dc1n3:
    container_name: dc1n3
    image: antidotedb/antidote:latest
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc1n3"
    ports:
      - "8301:8087"
      - "8302:3001"

  link-cluster-1:
    image: peterzel/antidote-connect
    command: ['--createDc', 'dc1n1:8087', 'antidote@dc1n2', 'antidote@dc1n3']
    depends_on:
    - dc1n1
    - dc1n2
    - dc1n3
